/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.monotes;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author oscar poblete saenz
 */
public class LoadC extends javax.swing.JFrame {
    ImageIcon loadvector= new ImageIcon("Load.png");
    
   
    public LoadC(String username) {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(386, 524);
        UsernameLabel.setText(username);
        LabelLoadPic.setIcon(loadvector);
        LabelLoadPic.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        LabelLoadPic = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PeriodTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SendDataButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TopassTextField = new javax.swing.JTextField();
        EvaluationsTextField = new javax.swing.JTextField();
        CourseTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DoneTextField = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Load course");
        setResizable(false);

        panel1.setBackground(new java.awt.Color(248, 171, 20));

        LabelLoadPic.setText("jLabel1");

        jLabel1.setText("Couse name:");

        jLabel2.setText("Period:");

        jLabel3.setText("Done:");

        SendDataButton.setText("Send data");
        SendDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendDataButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Grade to pass:");

        jLabel5.setText("Evaluations:");

        UsernameLabel.setBackground(new java.awt.Color(248, 171, 20));
        UsernameLabel.setForeground(new java.awt.Color(248, 171, 20));
        UsernameLabel.setFocusable(false);
        UsernameLabel.setInheritsPopupMenu(false);
        UsernameLabel.setRequestFocusEnabled(false);
        UsernameLabel.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LabelLoadPic, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(EvaluationsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PeriodTextField)
                    .addComponent(CourseTextField)
                    .addComponent(TopassTextField)
                    .addComponent(SendDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(LabelLoadPic, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CourseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PeriodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EvaluationsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(DoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TopassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addComponent(SendDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendDataButtonActionPerformed
        // TODO add your handling code here:
        try{
            
        if (CourseTextField.getText().isEmpty() || PeriodTextField.getText().isEmpty() || EvaluationsTextField.getText().isEmpty()|| DoneTextField.getText().isEmpty()
            ||TopassTextField.getText().isEmpty()||Integer.parseInt(EvaluationsTextField.getText())<Integer.parseInt(DoneTextField.getText())
            || Double.parseDouble(TopassTextField.getText())<0 ||Double.parseDouble(TopassTextField.getText())>10) {
                    JOptionPane.showMessageDialog(null,"Please fill in the fields properly","Error",JOptionPane.ERROR_MESSAGE);
            } else {
        String cname=CourseTextField.getText();
        int period=Integer.parseInt(PeriodTextField.getText());
        int evaluations=Integer.parseInt(EvaluationsTextField.getText());
        int done=Integer.parseInt(DoneTextField.getText());
        double topass=Double.parseDouble(TopassTextField.getText());
        double ppercent=0,percent=0,pgrade=0,grade=0,avg=0,pending=0,needed=0;
        boolean flag=false; //flag to check if inputs are valid 
        
            for(int i=0;i<done;i++){
                 ppercent=Double.parseDouble(JOptionPane.showInputDialog("Enter percentage of evaluation "+(i+1)+":")); //partial percentage (no counter to avoid overlay)
                 pgrade=Double.parseDouble(JOptionPane.showInputDialog("Enter grade of evaluation "+(i+1)+":")); //partial grades (no counter to avoid overlay)
            if((ppercent>=0 && ppercent<=100) && (pgrade>=0&&pgrade<=10) ){
                 avg=avg+pgrade*(ppercent/100); //operation to calculate grade at the moment (with partial and pending evaluations)
                 percent=percent+ppercent; //progress counter
                 flag=true;
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid value\nFor percentage: 0-100\nFor grade: 0-10","Error",JOptionPane.ERROR_MESSAGE);
                flag=false;
                break;
                }
           }
            
        if(flag){   
              grade=avg/(percent/100);// grade at the moment
              pending=100-percent; //percentage of pending evaluations
              //there is a difference in the order of calculation when the student does not have pending evaluations
              if(pending==0){ 
              needed=(10-avg)/(topass/10);//grade needed to pass the course (With parentheses in numerator)
              }else{
              needed=10-avg/(topass/10);//grade needed to pass the course (Without parentheses in numerator)
              }
              
              System.out.println("\nGrade:"+grade);
              System.out.println("Pending:"+pending);
              System.out.println("Average:"+avg);
              System.out.println("To pass:"+topass);
              System.out.println("Percent:"+percent);
              System.out.println("Needed:"+needed);
            
        String sql="INSERT INTO courses VALUES('"+UsernameLabel.getText()+"','"+cname+"',"+period+","+evaluations+","+done+","+grade+","+pending+","+needed+")";
        Database db = new Database();
        boolean resp=db.Connect();
        if(resp){
            db.query(sql);
            JOptionPane.showMessageDialog(null, "Course has been added","Success",JOptionPane.INFORMATION_MESSAGE);
            CourseTextField.setText("");
            PeriodTextField.setText("");
            EvaluationsTextField.setText("");
            DoneTextField.setText("");
            TopassTextField.setText("");
            db.Disconnect();
            }
          }
        }
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error: "+e.toString());
                }
    }//GEN-LAST:event_SendDataButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoadC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoadC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoadC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoadC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoadC().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CourseTextField;
    private javax.swing.JTextField DoneTextField;
    private javax.swing.JTextField EvaluationsTextField;
    private javax.swing.JLabel LabelLoadPic;
    private javax.swing.JTextField PeriodTextField;
    private javax.swing.JButton SendDataButton;
    private javax.swing.JTextField TopassTextField;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
