/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.monotes;

import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author oscar poblete saenz
 */
public class UpdateC extends javax.swing.JFrame {
     ImageIcon updatevector= new ImageIcon("Update.png");
    
    public UpdateC(String username) {
        initComponents();
        setSize(386, 524);
        this.setLocationRelativeTo(null);
        UsernameLabel.setText(username);
        LabelUpdatePic.setIcon(updatevector);
        LabelUpdatePic.setText("");
        fillComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        LabelUpdatePic = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PeriodTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CourseComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        EvaluationsTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TopassTextField = new javax.swing.JTextField();
        UpdateDataButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        DoneTextField = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update course");
        setResizable(false);

        panel1.setBackground(new java.awt.Color(248, 171, 20));

        LabelUpdatePic.setText("jLabel1");

        jLabel1.setText("Period:");

        jLabel2.setText("Course name:");

        CourseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Evaluations:");

        jLabel4.setText("Grade to pass:");

        UpdateDataButton.setText("Update data");
        UpdateDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDataButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Done:");

        UsernameLabel.setBackground(new java.awt.Color(248, 171, 20));
        UsernameLabel.setForeground(new java.awt.Color(248, 171, 20));
        UsernameLabel.setFocusable(false);
        UsernameLabel.setInheritsPopupMenu(false);
        UsernameLabel.setRequestFocusEnabled(false);
        UsernameLabel.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CourseComboBox, 0, 214, Short.MAX_VALUE)
                            .addComponent(PeriodTextField)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UpdateDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TopassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(EvaluationsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DoneTextField)))))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelUpdatePic, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(LabelUpdatePic, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PeriodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EvaluationsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(DoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TopassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addComponent(UpdateDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void fillComboBox(){
                Database db=new Database();
        try{
        boolean resp = db.Connect();
        String sql="SELECT c_id FROM courses c WHERE username_fk='"+UsernameLabel.getText()+"' ORDER BY c_id ASC";
        ResultSet rs = db.resultset(sql);
        CourseComboBox.addItem("Select course");
        while(rs.next()){
            CourseComboBox.addItem(rs.getString("c_id"));
        }      
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, " Error: "+e.toString());
        }finally{
            if(db.Connect()!=false){
                db.Disconnect();   
            }
        }
            
    }
    private void CourseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseComboBoxActionPerformed

    private void UpdateDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDataButtonActionPerformed
        // TODO add your handling code here:
                try{
            
        if (CourseComboBox.getSelectedItem().toString().equals("Select course")||PeriodTextField.getText().isEmpty() || EvaluationsTextField.getText().isEmpty()|| DoneTextField.getText().isEmpty()
            ||TopassTextField.getText().isEmpty()||Integer.parseInt(EvaluationsTextField.getText())<Integer.parseInt(DoneTextField.getText())
            || Double.parseDouble(TopassTextField.getText())<0 ||Double.parseDouble(TopassTextField.getText())>10) {
                    JOptionPane.showMessageDialog(null,"Please fill in the fields properly","Error",JOptionPane.ERROR_MESSAGE);
            } else {
        String cname=CourseComboBox.getSelectedItem().toString();
        int period=Integer.parseInt(PeriodTextField.getText());
        int evaluations=Integer.parseInt(EvaluationsTextField.getText());
        int done=Integer.parseInt(DoneTextField.getText());
        double topass=Double.parseDouble(TopassTextField.getText());
        double ppercent=0,percent=0,pgrade=0,grade=0,avg=0,pending=0,needed=0;
        boolean flag=false;
        
            for(int i=0;i<done;i++){
                 ppercent=Double.parseDouble(JOptionPane.showInputDialog("Enter percentage of evaluation "+(i+1)+":")); //partial percentage (no counter to avoid overlay)
                 pgrade=Double.parseDouble(JOptionPane.showInputDialog("Enter grade of evaluation "+(i+1)+":")); //partial grades (no counter to avoid overlay)
            if((ppercent>=0 && ppercent<=100) && (pgrade>=0&&pgrade<=10) ){
                 avg=avg+pgrade*(ppercent/100); //operation to calculate grade at the moment (with partial and pending evaluations)
                 percent=percent+ppercent; //progress counter
                 flag=true;
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid value\nFor percentage: 0-100\nFor grade: 0-10","Error",JOptionPane.ERROR_MESSAGE);
                flag=false;
                break;
                }
           }
            
        if(flag){   
              grade=avg/(percent/100);// grade at the moment
              pending=100-percent; //percentage of pending evaluations
              needed=10-avg/(topass/10);//grade needed to pass the course
              System.out.println(needed);
            
        String sql="UPDATE courses SET period="+period+",evaluations="+evaluations+",d_evaluations="+done+",grade="+grade+","
                + "pending="+pending+",needed="+needed+" WHERE c_id='"+cname+"' AND username_fk='"+UsernameLabel.getText()+"'";
        Database db = new Database();
        boolean resp=db.Connect();
        
        if(resp){
            db.query(sql);
            JOptionPane.showMessageDialog(null, "Course has been updated","Success",JOptionPane.INFORMATION_MESSAGE);
            CourseComboBox.setSelectedItem("Select course");
            PeriodTextField.setText("");
            EvaluationsTextField.setText("");
            DoneTextField.setText("");
            TopassTextField.setText("");
            db.Disconnect();
            }
          }
        }
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error: "+e.toString());
                }
    }//GEN-LAST:event_UpdateDataButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UpdateC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UpdateC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UpdateC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UpdateC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UpdateC().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CourseComboBox;
    private javax.swing.JTextField DoneTextField;
    private javax.swing.JTextField EvaluationsTextField;
    private javax.swing.JLabel LabelUpdatePic;
    private javax.swing.JTextField PeriodTextField;
    private javax.swing.JTextField TopassTextField;
    private javax.swing.JButton UpdateDataButton;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
